#!/usr/bin/bash

# TODO Expandir para um plugin do xenv
SCRIPT_NAME=$(realpath $0)
SCRIPT_FOLDER=$(dirname $SCRIPT_NAME)
PROJECT_HOME=$(dirname $SCRIPT_FOLDER)

export TASKRC="${PROJECT_HOME}/todo/taskrc"

cat << EOF > "${TASKRC}"
data.location=$PROJECT_HOME/todo
EOF

